services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-reverse-proxy
    networks:
      - open-homeserver-net
      - closed-homeserver-net
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  open-homeserver-net:
    external: true
  closed-homeserver-net:
    external: true
