events { }

http {
  server {
    listen 8181;

    location /glance {
      proxy_pass http://glance:8080;
    }

  }
}

stream {
  server {
    listen 25565;
    proxy_pass paper-server:25565;
  }
}
