events { }

http {
  server {
    listen 7001;
    location / {
      proxy_pass http://glance:8080;
    }
  }
  server {
    listen 7002;
    location / {
      proxy_pass http://bluemap:8100;
    }
  }
  server {
    listen 7000;
    location / {
      proxy_pass http://portfolio:80;
    }
  }
}

stream {
  server {
    listen 25565;
    proxy_pass paper-server:25565;
  }
  # server {
  #   listen 25564;
  #   proxy_pass modded-server:25565;
  # }
}
