events { }

http {
  server {
    listen 7001;
    location / {
      proxy_pass http://glance:8080;
    }
  }
}

stream {
  server {
    listen 25565;
    proxy_pass paper-server:25565;
  }
  server {
    listen 25564;
    proxy_pass modded-server:25565;
  }
}
