services:
  mc:
    image: itzg/minecraft-server
    container_name: paper-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      MEMORY: 96G
      VERSION: 1.21.10
      DIFFICULTY: hard
      MOTD: "§l§cMcDaServeur de retour"
    networks:
      - closed-homeserver-net
    volumes:
      - ./paper-server-data:/data
    restart: unless-stopped
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap
    container_name: bluemap-paper-server
    restart: always
    command: -r -u -w
    volumes:
      - ./bluemap/config:/app/config
      - ./bluemap/data:/app/data
      - ./bluemap/web:/app/web
      - ./paper-server-data/world:/app/world:ro
      - ./paper-server-data/world_nether:/app/world_nether:ro
      - ./paper-server-data/world_the_end:/app/world_the_end:ro
    depends_on:
      mc:
        condition: service_healthy
        restart: true

networks:
  closed-homeserver-net:
    external: true
