services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    networks:
      - closed-homeserver-net

networks:
  closed-homeserver-net:
    external: true
